using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Sichem;

namespace StbImageResizeSharp.Generator
{
	class Program
	{
		private static void Write(Dictionary<string, string> input, StringBuilder output)
		{
			foreach (var pair in input)
			{
				output.Append(pair.Value);
			}
		}

		private static string PostProcess(string data)
		{
			data = Utility.ReplaceNativeCalls(data);

			data = data.Replace("((void*)(0))", "null");
			data = data.Replace("((void *)(0))", "null");

			return data;
		}

		static void Process()
		{
			var parameters = new ConversionParameters
			{
				AdditionalIncludeFolders = new string[]
				{
					@"C:\Projects\StbSharp\FreeTypeSharp\FreeTypeTest\FreeTypeTest\freetype\include"
				},
				InputPath = @"C:\Projects\StbSharp\FreeTypeSharp\FreeTypeTest\FreeTypeTest\freetype\src\base\ftbase.c",
				Defines = new string[]
				{
					"_LIB",
					"_CRT_SECURE_NO_WARNINGS",
					"FT2_BUILD_LIBRARY"
				},
				SkipEnums = new string[]
				{
					"FT_Encoding_",
				},
				SkipStructs = new string[]
				{
					"FT_StreamDesc_",
					"FT_StreamRec_",
				},
				SkipGlobalVariables = new string[]
				{
				},
				SkipFunctions = new string[]
				{
				},
				Classes = new string[]
				{
					"FT_FaceRec_",
					"FT_Outline_Funcs_",
					"FT_Renderer_Class_",
					"FT_RendererRec_",
					"FT_ModuleRec_",
					"FT_Module_Class_",
					"FT_MemoryRec_",
					"FT_LibraryRec_",
					"FT_StreamRec_",
					"ft_raccess_guess_rec_",
					"FT_CharMapRec_",
				},
				GlobalArrays = new string[]
				{
				}
			};

			var cp = new ClangParser();

			var result = cp.Process(parameters);

			// Write output
			var sb = new StringBuilder();
			sb.AppendLine(string.Format("// Generated by Sichem at {0}", DateTime.Now));
			sb.AppendLine();

			sb.AppendLine("using System;");
			sb.AppendLine("using System.Runtime.InteropServices;");

			sb.AppendLine();

			sb.Append("namespace FreeTypeSharp\n{\n\t");
			sb.AppendLine("unsafe partial class FreeType\n\t{");

			Write(result.Constants, sb);
			Write(result.GlobalVariables, sb);
			Write(result.Enums, sb);
			Write(result.Structs, sb);
			Write(result.Methods, sb);

			sb.Append("}\n}");
			var data = sb.ToString();

			// Post processing
			Logger.Info("Post processing...");
			data = PostProcess(data);

			File.WriteAllText(@"..\..\..\..\..\src\FtBase.Generated.cs", data);
		}

		static void Main(string[] args)
		{
			try
			{
				Process();
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex.Message);
				Console.WriteLine(ex.StackTrace);
			}

			Console.WriteLine("Finished. Press any key to quit.");
			Console.ReadKey();
		}
	}
}